// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using item_management.Data;

#nullable disable

namespace item_management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250704091019_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("item_management.Models.OITM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OUGPId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("OUGPId");

                    b.ToTable("OITM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            ItemCode = "SP001",
                            ItemGroup = "Điện tử - Smartphone",
                            ItemName = "iPhone 15 Pro Max 256GB",
                            OUGPId = "ELEC001",
                            Price = 29999000m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            ItemCode = "SP002",
                            ItemGroup = "Điện tử - Laptop",
                            ItemName = "MacBook Air M2 13 inch",
                            OUGPId = "ELEC001",
                            Price = 27999000m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            ItemCode = "SP003",
                            ItemGroup = "Điện tử - Smartphone",
                            ItemName = "Samsung Galaxy S24 Ultra",
                            OUGPId = "ELEC001",
                            Price = 26999000m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            ItemCode = "SP004",
                            ItemGroup = "Điện tử - Laptop",
                            ItemName = "Dell XPS 13 Plus",
                            OUGPId = "ELEC001",
                            Price = 35999000m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            ItemCode = "SP005",
                            ItemGroup = "Điện tử - Tablet",
                            ItemName = "iPad Pro 12.9 inch M2",
                            OUGPId = "ELEC001",
                            Price = 25999000m
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            ItemCode = "SP006",
                            ItemGroup = "Điện tử - Tai nghe",
                            ItemName = "AirPods Pro 2",
                            OUGPId = "ELEC001",
                            Price = 5999000m
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            ItemCode = "SP007",
                            ItemGroup = "Điện tử - Đồng hồ thông minh",
                            ItemName = "Apple Watch Series 9",
                            OUGPId = "ELEC001",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            ItemCode = "SP008",
                            ItemGroup = "Nội thất - Bàn",
                            ItemName = "Bàn làm việc gỗ Oak",
                            OUGPId = "FURN001",
                            Price = 4500000m
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            ItemCode = "SP009",
                            ItemGroup = "Nội thất - Ghế",
                            ItemName = "Ghế ergonomic Herman Miller",
                            OUGPId = "FURN001",
                            Price = 12000000m
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            ItemCode = "SP010",
                            ItemGroup = "Nội thất - Kệ",
                            ItemName = "Kệ sách gỗ tự nhiên",
                            OUGPId = "FURN001",
                            Price = 2800000m
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            ItemCode = "SP011",
                            ItemGroup = "Nội thất - Tủ",
                            ItemName = "Tủ quần áo 3 cửa",
                            OUGPId = "FURN001",
                            Price = 8500000m
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            ItemCode = "SP012",
                            ItemGroup = "Nội thất - Sofa",
                            ItemName = "Sofa da 3 chỗ ngồi",
                            OUGPId = "FURN001",
                            Price = 15000000m
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            ItemCode = "SP013",
                            ItemGroup = "Gia dụng - Tủ lạnh",
                            ItemName = "Tủ lạnh Samsung 360L",
                            OUGPId = "HOME001",
                            Price = 15500000m
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            ItemCode = "SP014",
                            ItemGroup = "Gia dụng - Máy giặt",
                            ItemName = "Máy giặt LG 9kg",
                            OUGPId = "HOME001",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            ItemCode = "SP015",
                            ItemGroup = "Gia dụng - Điều hòa",
                            ItemName = "Điều hòa Daikin 12000 BTU",
                            OUGPId = "HOME001",
                            Price = 12500000m
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            ItemCode = "SP016",
                            ItemGroup = "Gia dụng - Lò vi sóng",
                            ItemName = "Lò vi sóng Panasonic 25L",
                            OUGPId = "HOME001",
                            Price = 3500000m
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            ItemCode = "SP017",
                            ItemGroup = "Sách - Công nghệ",
                            ItemName = "Bộ sách lập trình C#",
                            OUGPId = "BOOK001",
                            Price = 850000m
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            ItemCode = "SP018",
                            ItemGroup = "Văn phòng phẩm - Bút",
                            ItemName = "Bút bi Parker",
                            OUGPId = "BOOK001",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            ItemCode = "SP019",
                            ItemGroup = "Thời trang - Áo sơ mi",
                            ItemName = "Áo sơ mi nam công sở",
                            OUGPId = "CLTH001",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 20,
                            IsActive = false,
                            ItemCode = "SP020",
                            ItemGroup = "Thời trang - Quần",
                            ItemName = "Quần jean nữ skinny",
                            OUGPId = "CLTH001",
                            Price = 680000m
                        });
                });

            modelBuilder.Entity("item_management.Models.OITW", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("OWHSId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OWHSId");

                    b.HasIndex("WarehouseCode");

                    b.HasIndex("ItemId", "WarehouseCode")
                        .IsUnique();

                    b.ToTable("OITW", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            QuantityOnHand = 45m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 1,
                            QuantityOnHand = 62m,
                            WarehouseCode = "WH-HCM"
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 1,
                            QuantityOnHand = 28m,
                            WarehouseCode = "WH-DN"
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 2,
                            QuantityOnHand = 32m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 2,
                            QuantityOnHand = 28m,
                            WarehouseCode = "WH-HCM"
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 3,
                            QuantityOnHand = 38m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 3,
                            QuantityOnHand = 55m,
                            WarehouseCode = "WH-HCM"
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 8,
                            QuantityOnHand = 25m,
                            WarehouseCode = "WH-BD"
                        },
                        new
                        {
                            Id = 9,
                            ItemId = 8,
                            QuantityOnHand = 15m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 10,
                            ItemId = 9,
                            QuantityOnHand = 8m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 11,
                            ItemId = 9,
                            QuantityOnHand = 12m,
                            WarehouseCode = "WH-HCM"
                        },
                        new
                        {
                            Id = 12,
                            ItemId = 13,
                            QuantityOnHand = 35m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 13,
                            ItemId = 13,
                            QuantityOnHand = 42m,
                            WarehouseCode = "WH-HCM"
                        },
                        new
                        {
                            Id = 14,
                            ItemId = 17,
                            QuantityOnHand = 150m,
                            WarehouseCode = "WH-HN"
                        },
                        new
                        {
                            Id = 15,
                            ItemId = 19,
                            QuantityOnHand = 200m,
                            WarehouseCode = "WH-HCM"
                        });
                });

            modelBuilder.Entity("item_management.Models.OUGP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<int>("BaseUom")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("BaseUom");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OUGP", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUom = 1,
                            Code = "ELEC001",
                            Name = "Điện tử"
                        },
                        new
                        {
                            Id = 2,
                            BaseUom = 1,
                            Code = "FURN001",
                            Name = "Nội thất"
                        },
                        new
                        {
                            Id = 3,
                            BaseUom = 1,
                            Code = "HOME001",
                            Name = "Gia dụng"
                        },
                        new
                        {
                            Id = 4,
                            BaseUom = 1,
                            Code = "BOOK001",
                            Name = "Sách văn phòng phẩm"
                        },
                        new
                        {
                            Id = 5,
                            BaseUom = 6,
                            Code = "CLTH001",
                            Name = "Quần áo"
                        });
                });

            modelBuilder.Entity("item_management.Models.OUOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OUOM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UOM001",
                            Name = "Cái"
                        },
                        new
                        {
                            Id = 2,
                            Code = "UOM002",
                            Name = "Hộp"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UOM003",
                            Name = "Bộ"
                        },
                        new
                        {
                            Id = 4,
                            Code = "UOM004",
                            Name = "Thùng"
                        },
                        new
                        {
                            Id = 5,
                            Code = "UOM005",
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UOM006",
                            Name = "Chiếc"
                        },
                        new
                        {
                            Id = 7,
                            Code = "UOM007",
                            Name = "Gói"
                        });
                });

            modelBuilder.Entity("item_management.Models.OWHS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WhsCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WhsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WhsCode")
                        .IsUnique();

                    b.ToTable("OWHS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WhsCode = "WH-HN",
                            WhsName = "Kho Hà Nội"
                        },
                        new
                        {
                            Id = 2,
                            WhsCode = "WH-HCM",
                            WhsName = "Kho TP.HCM"
                        },
                        new
                        {
                            Id = 3,
                            WhsCode = "WH-DN",
                            WhsName = "Kho Đà Nẵng"
                        },
                        new
                        {
                            Id = 4,
                            WhsCode = "WH-BD",
                            WhsName = "Kho Bình Dương"
                        },
                        new
                        {
                            Id = 5,
                            WhsCode = "WH-CT",
                            WhsName = "Kho Cần Thơ"
                        });
                });

            modelBuilder.Entity("item_management.Models.UGP1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltQty")
                        .HasColumnType("float");

                    b.Property<int>("AlternateUoM")
                        .HasColumnType("int");

                    b.Property<double>("BaseQty")
                        .HasColumnType("float");

                    b.Property<int>("FatherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateUoM");

                    b.HasIndex("FatherId", "AlternateUoM")
                        .IsUnique();

                    b.ToTable("UGP1", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltQty = 1.0,
                            AlternateUoM = 2,
                            BaseQty = 10.0,
                            FatherId = 1
                        },
                        new
                        {
                            Id = 2,
                            AltQty = 1.0,
                            AlternateUoM = 3,
                            BaseQty = 5.0,
                            FatherId = 1
                        },
                        new
                        {
                            Id = 3,
                            AltQty = 1.0,
                            AlternateUoM = 4,
                            BaseQty = 50.0,
                            FatherId = 1
                        },
                        new
                        {
                            Id = 4,
                            AltQty = 1.0,
                            AlternateUoM = 3,
                            BaseQty = 2.0,
                            FatherId = 2
                        },
                        new
                        {
                            Id = 5,
                            AltQty = 1.0,
                            AlternateUoM = 4,
                            BaseQty = 20.0,
                            FatherId = 2
                        },
                        new
                        {
                            Id = 6,
                            AltQty = 1.0,
                            AlternateUoM = 2,
                            BaseQty = 8.0,
                            FatherId = 3
                        },
                        new
                        {
                            Id = 7,
                            AltQty = 1.0,
                            AlternateUoM = 4,
                            BaseQty = 30.0,
                            FatherId = 3
                        },
                        new
                        {
                            Id = 8,
                            AltQty = 1.0,
                            AlternateUoM = 7,
                            BaseQty = 12.0,
                            FatherId = 4
                        },
                        new
                        {
                            Id = 9,
                            AltQty = 1.0,
                            AlternateUoM = 4,
                            BaseQty = 100.0,
                            FatherId = 4
                        },
                        new
                        {
                            Id = 10,
                            AltQty = 1.0,
                            AlternateUoM = 7,
                            BaseQty = 3.0,
                            FatherId = 5
                        },
                        new
                        {
                            Id = 11,
                            AltQty = 1.0,
                            AlternateUoM = 4,
                            BaseQty = 50.0,
                            FatherId = 5
                        });
                });

            modelBuilder.Entity("item_management.Models.OITM", b =>
                {
                    b.HasOne("item_management.Models.OUGP", null)
                        .WithMany()
                        .HasForeignKey("OUGPId")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("item_management.Models.OITW", b =>
                {
                    b.HasOne("item_management.Models.OITM", "Item")
                        .WithMany("OITW")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("item_management.Models.OWHS", null)
                        .WithMany("OITW")
                        .HasForeignKey("OWHSId");

                    b.HasOne("item_management.Models.OWHS", null)
                        .WithMany()
                        .HasForeignKey("WarehouseCode")
                        .HasPrincipalKey("WhsCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("item_management.Models.OUGP", b =>
                {
                    b.HasOne("item_management.Models.OUOM", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId");

                    b.HasOne("item_management.Models.OUOM", null)
                        .WithMany()
                        .HasForeignKey("BaseUom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("item_management.Models.UGP1", b =>
                {
                    b.HasOne("item_management.Models.OUOM", "AlternateUnit")
                        .WithMany()
                        .HasForeignKey("AlternateUoM")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("item_management.Models.OUGP", "Father")
                        .WithMany("UGP1")
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateUnit");

                    b.Navigation("Father");
                });

            modelBuilder.Entity("item_management.Models.OITM", b =>
                {
                    b.Navigation("OITW");
                });

            modelBuilder.Entity("item_management.Models.OUGP", b =>
                {
                    b.Navigation("UGP1");
                });

            modelBuilder.Entity("item_management.Models.OWHS", b =>
                {
                    b.Navigation("OITW");
                });
#pragma warning restore 612, 618
        }
    }
}
